
export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm5R4urUDirLdD79ET5tP
Loca0PDFdcgSFNyN0es4hpEcrwsBoD/GHK2elOvYVUolyQ3pysSVNg+4C3nlmd4m
wkhxZw/Mc5os7q9pAqtS2LU30u2wRKAzU8nDm2doQ/hTvIyUg0gFOn7RVZqeYwRW
93+MuOZkBtbkVY3jFUFhSqUQfvRVg9a1euX1MSwaDiucFqPmZSPjkqZ/BkWTaziL
B/SJoOsxS81hyHF+xoqV12tK6R1rNC4Arm+Ol55kzqTLKhKV82NldOEVfSJ/aMT+
tOCyCHbbKexHPKPFjh6BgWUv1Bo1NIEkv0VPXGPCmpuMyjD6mN6a2/LP+ZhzzmnI
/wIDAQAB
-----END PUBLIC KEY-----
`;